
 /*------------------------------------------------------------------------
    File        : IOppervlakte
    Purpose     : 
    Syntax      : 
    Author(s)   : bronco
    Created     : Mon Feb 19 19:50:18 +01:00 2024
    Notes       : 
  ----------------------------------------------------------------------*/

interface dag1.IOppervlakte:

    method public decimal GetOppervlakte().

end interface.  // IOppervlakte
