version: '3.8'

services:

  devcontainer:
    image: ${DEVCONTAINER_IMAGE}
    volumes:
      - ../..:/workspaces:cached
      - ${LICENSE_FILE}:/usr/dlc/progress.cfg
    ports:
      - 3099:3099
    command: sleep infinity
