version: '3.8'

services:

  devcontainer:
    image: docker.io/devbfvio/openedge-devcontainer:12.8.0-rc1
    volumes:
      - ../..:/workspaces:cached
      - ../license/progress.cfg:/usr/dlc/progress.cfg
    ports:
      - 3099:3099
    command: sleep infinity
